NAVER_CLIENT_ID: "7PuKqO2BxrvjGHRjGENN"
NAVER_ClIENT_SECRET: "GM43jTOBLE"
Kakao_Key: "674b81e77c8b32353d3c6bca3abcd076"
Facebook_Key: "2101845879826014"
Facebook_Secret: "288705d711df2f0cb96e5c1c4fd10c79"
Google_Key: "945320196832-7huib52hph6tbqc1em3aabkv7vovoj77.apps.googleusercontent.com"
Google_Secret: "ivwBt5tdVFH3tSKYmkMj_zcU"
